import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';import {PortalStore} from '../src/portal-store.mjs';import {hostFeatures} from '../src/host-features.mjs';
const directory=fs.mkdtempSync(path.join(os.tmpdir(),'collab-'));
try{let s=new PortalStore({directory,features:()=>hostFeatures()});for(const id of ['a','b','c'])s.register(id,s.joinPassword);
 assert.throws(()=>s.collabRequest('a','b'),/explanation/);s.acceptCollabWarning('a');const p=s.collabRequest('a','b');assert.throws(()=>s.collabRespond('a',p.id,'accept'));assert.throws(()=>s.collabRespond('c',p.id,'accept'));assert.throws(()=>s.collabRespond('b',p.id,'accept'),/explanation/);s.acceptCollabWarning('b');s.collabRespond('b',p.id,'accept');for(const a of ['a','b'])for(const kind of ['video','fallback'])assert(s.allowed(a,a==='a'?'b':'a',kind));assert.equal(s.get('a').settings.overlays.length,0);
 s.collabRequest('a','b',true);assert.throws(()=>s.collabRespond('a',p.id,'accept-super'));s.collabRespond('b',p.id,'accept-super');s.endSession('a');assert(s.allowed('a','b','video'));s=new PortalStore({directory,features:()=>hostFeatures()});assert(s.allowed('b','a','fallback'));s.collabRespond('b',p.id,'end');assert(!s.allowed('a','b','video'));assert(!s.allowed('b','a','fallback'));
 const next=s.collabRequest('a','b');s.collabRespond('b',next.id,'accept');s.endSession('b');assert(!s.allowed('a','b','video'));assert.throws(()=>s.collabRequest('a','b',true));
 s.collabRequest('a','b');s.collabRespond('b',next.id,'accept');s=new PortalStore({directory,features:()=>hostFeatures()});assert(!s.allowed('a','b','fallback'));assert(s.get('a').collabWarning===1);
 const again=s.collabRequest('a','b');s.collabRespond('b',again.id,'accept');const req=s.db.requests.find(r=>r.owner==='a');assert.throws(()=>s.respond('b',req.id,'approve'));s.db.partnerships[0].expiresAt=Date.now()-1;assert(!s.allowed('a','b','video'));const v=s.publicView('a',()=>({state:'ready'}));assert(v.requests.every(r=>r.status!=='approved'));s.displayName('a','A Friendly Name');assert.equal(s.publicView('a',()=>({})).me.displayName,'A Friendly Name');
 console.log('PASS mutual session permissions, prerequisite warning, recipient-only acceptance, persistent upgrade, either-party revoke, session/restart/expiry, no automatic placement, legacy endpoint isolation, display names.');
}finally{fs.rmSync(directory,{recursive:true,force:true});}
