import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {createRequire} from 'node:module';import {PortalStore} from '../src/portal-store.mjs';import {hostFeatures} from '../src/host-features.mjs';import {HostAdmin} from '../src/host-admin.mjs';import {createPortalServer} from '../src/portal-server.mjs';
const require=createRequire(import.meta.url),{chromium}=require('../../uc-build-tools/node_modules/playwright');const directory=fs.mkdtempSync(path.join(os.tmpdir(),'ui5-'));let server,browser;
try{
 const config={multi:{maxSessions:3},hostFeatures:{guestInvites:true}};const store=new PortalStore({directory,features:()=>hostFeatures(config)});store.register('friend',store.joinPassword);store.acceptCollabWarning('friend');const host=new HostAdmin({store,config});let live=false;server=await createPortalServer({config:{bind:'127.0.0.1',port:0},store,status:()=>({state:live?'live':'ready',broadcast:live,width:1920,height:1080,fps:30,pictureInPicture:true,collabFallback:true}),action:async()=>{},changed:()=>{},busy:()=>false,validateDestination:async()=>{},rtmpPort:1935});const origin='http://127.0.0.1:'+server.server.address().port;
 browser=await chromium.launch({headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.stack)});page.on('dialog',d=>d.accept());
 await page.addInitScript(({origin})=>{
 const state={accounts:{},configured:{twitch:true,youtube:true},auth:{},chats:{twitch:{running:true,status:'Running'},youtube:{running:true,status:'Running'}},messages:[{id:'m',platform:'twitch',author:'Friend',text:'Hello, studio!',time:Date.now()}]};window.platformCalls=[];window.oauthMissing=true;window.obsCalls=[];window.mockOBS={online:false,stream:false,record:false,current:'Camera',scenes:['Camera','Break'],shown:true,locked:false,volume:-12,muted:false};
 window.relayDesktop={loadServers:async()=>JSON.parse(localStorage.getItem('test-servers')||'{"schemaVersion":1,"servers":[],"selectedKey":""}'),saveServers:async s=>localStorage.setItem('test-servers',JSON.stringify(s)),loadLocalProfile:async()=>JSON.parse(localStorage.getItem('test-profile')||'null'),saveLocalProfile:async s=>localStorage.setItem('test-profile',JSON.stringify(s)),copy:async()=>{},onPlatforms:()=>{},platform:async(op,input)=>{platformCalls.push({op,input});if(op==='connect'&&oauthMissing)throw Error('Sign-in is not configured in this build.');return state;},studio:async()=>({custom:[],drafts:[]}),obs:async(op,input)=>{window.obsCalls.push({op,input});const m=window.mockOBS;if(op==='connect')m.online=true;if(op==='disconnect')m.online=false;if(op==='state')return {connected:m.online};if(op==='configure')return {configured:true};if(op==='start')m.stream=true;if(op==='stream-stop')m.stream=false;if(op==='record-start')m.record=true;if(op==='record-stop')m.record=false;if(op==='scene-switch')m.current=input.sceneName;if(op==='scene-create')m.scenes.push(input.sceneName);if(op==='source-visible')m.shown=input.enabled;if(op==='source-lock')m.locked=input.locked;if(op==='volume')m.volume=input.db;if(op==='mute')m.muted=input.muted;
 if(op==='settings')return {video:{baseWidth:1920,baseHeight:1080,outputWidth:1280,outputHeight:720,fpsNumerator:30,fpsDenominator:1},record:{recordDirectory:'/tmp/records'}};
 if(op==='snapshot')return {connected:m.online,current:m.current,sceneName:input.sceneName||m.current,scenes:m.scenes.map(sceneName=>({sceneName})),items:[{sourceName:'Camera source',sceneItemId:1,sceneItemIndex:0,sceneItemEnabled:m.shown,sceneItemLocked:m.locked,sceneItemTransform:{positionX:0,positionY:0,scaleX:1,scaleY:1,rotation:0}}],inputs:[{inputName:'Camera source'}],mixer:[{inputName:'Mic',inputVolumeDb:m.volume,inputMuted:m.muted}],stream:{outputActive:m.stream},record:{outputActive:m.record}};
 if(op==='preview')return {image:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aXioAAAAASUVORK5CYII='};return {connected:m.online};},request:async q=>{const res=await fetch(origin+q.route,{method:q.body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+q.token,'Content-Type':'application/json'},body:q.body===undefined?undefined:JSON.stringify(q.body)});const data=await res.json();if(!res.ok)throw Error(data.error);return data;}};
 },{origin});
 page.setDefaultTimeout(7000);await page.goto(origin);await page.waitForFunction(()=>document.body.dataset.ready==='true');

 await page.waitForFunction(()=>document.body.dataset.compactReady==='true');
 assert(!(await page.locator('#studioPage').isVisible()));assert(!(await page.locator('#menuBar').isVisible()));
 await page.screenshot({path:'/tmp/rc8-setup.png'});
 await page.locator('#setupName').fill('Alice');await page.locator('#setupNext').click();await page.locator('#linkTwitch').click();assert(!(await page.locator('#tab-twitch').isVisible()));assert(!(await page.locator('#applicationConnections').isVisible()));await page.waitForFunction(()=>document.querySelector('#linkFeedback').textContent.includes('not configured'));assert(await page.evaluate(()=>platformCalls.some(c=>c.op==='connect'&&c.input.platform==='twitch')));await page.evaluate(()=>oauthMissing=false);await page.locator('#linkTwitch').click();await page.waitForFunction(()=>document.querySelector('#linkFeedback').textContent.includes('browser'));
 await page.locator('#setupNext').click();await page.locator('#chooseAutoOBS').click();await page.waitForFunction(()=>window.obsConnected);assert(await page.evaluate(()=>obsCalls.some(c=>c.input?.discover)));
 await page.locator('#setupNext').click();await page.locator('#joinRelay').click();await page.locator('#backLocal').click();assert(!(await page.locator('#joinRelayWindow').isVisible()));await page.locator('#joinRelay').click();await page.locator('#serverNickname').fill('Local relay');await page.locator('#address').fill(origin);await page.locator('#password').fill(store.joinPassword);await page.locator('#connect').click();await page.waitForFunction(()=>connected);await page.locator('#setupNext').click();
 assert(await page.locator('#studioPage').isVisible());assert(!(await page.locator('#obsSourcesPanel').isVisible()));assert.equal(await page.locator('#chatSurface').evaluate(n=>n.parentElement.id),'dockLeft');
 await page.locator('#obsMixer input[type=range]').waitFor();const slider=await page.locator('#obsMixer input[type=range]').boundingBox();assert(slider.height>slider.width);assert.equal(await page.locator('#dockBottom>[data-dock]:visible').count(),4);assert.equal(await page.locator('#dockBottom>.panel-separator').count(),3);
 await page.locator('#obsMixer').getByRole('button',{name:'Mute',exact:true}).click();await page.waitForFunction(()=>mockOBS.muted);await page.locator('#obsScenes').getByRole('button',{name:'Break',exact:true}).click();await page.waitForFunction(()=>mockOBS.current==='Break');
 await page.locator('#settingsGear').click();assert(await page.locator('#layoutPreview').isVisible());await page.locator('[data-setting=output]').click();assert(await page.locator('#resolutionBar').isVisible());assert.equal(await page.locator('#layoutResolution').inputValue(),'auto');await page.locator('[data-close=settingsPageWindow]').click();
 await page.getByRole('button',{name:'Chat settings',exact:true}).click();assert(await page.locator('#chatSettingsWindow').isVisible());await page.locator('[data-close=chatSettingsWindow]').click();await page.locator('#chatText').fill('Arrow send');await page.getByRole('button',{name:'Send chat message',exact:true}).click();await page.waitForFunction(()=>platformCalls.some(c=>c.op==='send'&&c.input.text==='Arrow send'));await page.locator('#moderatorToggle').click();assert.equal(await page.locator('#moderatorToggle').getAttribute('aria-pressed'),'true');
 const sep=page.locator('#dockBottom>.panel-separator').first(),before=await page.locator('#obsScenesPanel').boundingBox();await sep.focus();await page.keyboard.press('ArrowRight');assert((await page.locator('#obsScenesPanel').boundingBox()).width>before.width);
 await page.locator('.app-menu summary').filter({hasText:'Panels'}).click();await page.locator('.menu-popup').getByLabel('Show OBS sources',{exact:true}).check();assert(await page.locator('#obsSourcesPanel').isVisible());await page.locator('.menu-popup').getByLabel('Show OBS sources',{exact:true}).uncheck();await page.locator('.app-menu summary').filter({hasText:'Panels'}).click();
 await page.getByRole('button',{name:'Add relay scene',exact:true}).click();await page.locator('#nameActionValue').fill('Together');await page.locator('#nameActionForm').getByRole('button',{name:'Save',exact:true}).click();await page.locator('#sceneList').getByRole('button',{name:'Together',exact:true}).click({button:'right'});await page.locator('#compactContext').getByRole('menuitem',{name:'Rename',exact:true}).click();await page.locator('#nameActionValue').fill('Renamed');await page.locator('#nameActionForm').getByRole('button',{name:'Save',exact:true}).click();await page.locator('#sceneList').getByRole('button',{name:'Renamed',exact:true}).waitFor();await page.locator('[data-layer=main] .source-name').click({button:'right'});await page.locator('#compactContext').getByRole('menuitem',{name:'Lock / unlock',exact:true}).click();assert(await page.evaluate(()=>streamCanvas.selected().locked));
 assert(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight&&document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'/tmp/rc8-studio.png'});
 await page.reload();await page.waitForFunction(()=>document.body.dataset.compactReady==='true');assert(!(await page.locator('#setupGuide').isVisible()));await page.setViewportSize({width:1000,height:700});assert(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight&&document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);
 console.log('PASS rc8 setup isolation, direct account authorization and missing-ID feedback, automatic OBS sync, join/cancel, vertical mixer, four docks, dividers, chat, popup settings, scene/source context actions and persistence.');
}catch(e){console.error(e);throw e;}finally{await browser?.close();await new Promise(r=>server?server.server.close(r):r());fs.rmSync(directory,{recursive:true,force:true});}
