import assert from'node:assert/strict';import fs from'node:fs';import os from'node:os';import path from'node:path';import {createRequire}from'node:module';
import{PortalStore}from'../src/portal-store.mjs';import{HostAdmin}from'../src/host-admin.mjs';import{hostFeatures}from'../src/host-features.mjs';import{createPortalServer}from'../src/portal-server.mjs';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'../../uc-build-tools/node_modules/playwright');const dir=fs.mkdtempSync(path.join(os.tmpdir(),'uc-host-ui-'));let registry,server,browser;
try{const config={multi:{maxSessions:3},hostFeatures:{guestInvites:true},recordings:{maxStorageMB:20000,minFreeMB:256}};const store=new PortalStore({directory:dir+'/relay',features:()=>hostFeatures(config)});const host=new HostAdmin({store,config});server=await createPortalServer({config:{bind:'127.0.0.1',port:0},store,status:()=>({state:'ready',width:1920,height:1080,fps:30}),action:async()=>{},changed:()=>{},busy:()=>false,validateDestination:async()=>{},rtmpPort:1935});const origin='http://127.0.0.1:'+server.server.address().port;
 browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||'../release-runtime/UniversalCollab-Linux/stream-relay',args:['--no-sandbox','--disable-dev-shm-usage']});const page=await browser.newPage({viewport:{width:1280,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin);
 // Existing UI may require local profile before relay login.
 const local=page.locator('#localProfileForm');if(await local.isVisible()){await page.locator('#localDisplayName').fill('Host');await local.locator('button[type=submit]').click();}
 await page.locator('#username').fill('owner');await page.locator('#hostPanel summary').click();await page.locator('#hostClaimCode').fill(fs.readFileSync(dir+'/relay/host-setup-code.txt','utf8').trim());await page.getByRole('button',{name:'Claim this relay',exact:true}).click();await page.locator('#host-memberLimit').waitFor();assert.equal(host.db.ownerId,'owner');assert.equal(await page.locator('#hostClaimCode').inputValue(),'');
 assert.equal(await page.locator('#host-maxStorageMB').inputValue(),'20000');assert.equal(await page.locator('#hostLicenseKey').count(),0);assert(host.canStart('owner'));
 await page.locator('#host-defaultStorageMB').fill('500');await page.locator('#host-guestMaxMinutes').fill('60');await page.getByRole('button',{name:'Save server settings',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#host-defaultStorageMB')?.value==='500');await page.waitForTimeout(150);assert.equal(host.db.policy.defaultStorageMB,500);
 const member=store.register('member',store.joinPassword);await page.locator('#hostLoad').click();await page.locator('#quota-member').waitFor();page.on('dialog',d=>d.accept());await page.getByRole('button',{name:'Remove access',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#hostContent').textContent.includes('access removed'));assert(store.get(member.id).disabled);
 assert.deepEqual(errors,[]);await page.locator('#hostPanel').scrollIntoViewIfNeeded();await page.screenshot({path:path.resolve('../rc3-host-panel.png'),fullPage:true});await page.setViewportSize({width:500,height:1000});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));console.log('PASS real browser claim, free host controls, secret clearing, inherited settings, quotas, member removal and mobile layout.');
}finally{await browser?.close();await server?.close();fs.rmSync(dir,{recursive:true,force:true});}
