import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {createRequire} from 'node:module';import {PortalStore} from '../src/portal-store.mjs';import {hostFeatures} from '../src/host-features.mjs';import {HostAdmin} from '../src/host-admin.mjs';import {createPortalServer} from '../src/portal-server.mjs';
const require=createRequire(import.meta.url),{chromium}=require('../../uc-build-tools/node_modules/playwright');const directory=fs.mkdtempSync(path.join(os.tmpdir(),'ui5-'));let server,browser;
try{
 const config={multi:{maxSessions:3},hostFeatures:{guestInvites:true}};const store=new PortalStore({directory,features:()=>hostFeatures(config)});store.register('friend',store.joinPassword);store.acceptCollabWarning('friend');const host=new HostAdmin({store,config});let live=false;server=await createPortalServer({config:{bind:'127.0.0.1',port:0},store,status:()=>({state:live?'live':'ready',broadcast:live,width:1920,height:1080,fps:30,pictureInPicture:true,collabFallback:true}),action:async()=>{},changed:()=>{},busy:()=>false,validateDestination:async()=>{},rtmpPort:1935});const origin='http://127.0.0.1:'+server.server.address().port;
 browser=await chromium.launch({headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.message)});page.on('dialog',d=>d.accept());
 await page.addInitScript(({origin})=>{
 const state={accounts:{},configured:{twitch:true,youtube:true},auth:{},chats:{twitch:{running:true,status:'Running'},youtube:{running:true,status:'Running'}},messages:[{id:'m',platform:'twitch',author:'Friend',text:'Hello, studio!',time:Date.now()}]};window.obsCalls=[];window.mockOBS={online:false,stream:false,record:false,current:'Camera',scenes:['Camera','Break'],shown:true,locked:false,volume:-12,muted:false};
 window.relayDesktop={loadServers:async()=>JSON.parse(localStorage.getItem('test-servers')||'{"schemaVersion":1,"servers":[],"selectedKey":""}'),saveServers:async s=>localStorage.setItem('test-servers',JSON.stringify(s)),loadLocalProfile:async()=>JSON.parse(localStorage.getItem('test-profile')||'null'),saveLocalProfile:async s=>localStorage.setItem('test-profile',JSON.stringify(s)),copy:async()=>{},onPlatforms:()=>{},platform:async()=>state,studio:async()=>({custom:[],drafts:[]}),obs:async(op,input)=>{window.obsCalls.push({op,input});const m=window.mockOBS;if(op==='connect')m.online=true;if(op==='disconnect')m.online=false;if(op==='state')return {connected:m.online};if(op==='configure')return {configured:true};if(op==='start')m.stream=true;if(op==='stream-stop')m.stream=false;if(op==='record-start')m.record=true;if(op==='record-stop')m.record=false;if(op==='scene-switch')m.current=input.sceneName;if(op==='scene-create')m.scenes.push(input.sceneName);if(op==='source-visible')m.shown=input.enabled;if(op==='source-lock')m.locked=input.locked;if(op==='volume')m.volume=input.db;if(op==='mute')m.muted=input.muted;
 if(op==='settings')return {video:{baseWidth:1920,baseHeight:1080,outputWidth:1280,outputHeight:720,fpsNumerator:30,fpsDenominator:1},record:{recordDirectory:'/tmp/records'}};
 if(op==='snapshot')return {connected:m.online,current:m.current,sceneName:input.sceneName||m.current,scenes:m.scenes.map(sceneName=>({sceneName})),items:[{sourceName:'Camera source',sceneItemId:1,sceneItemIndex:0,sceneItemEnabled:m.shown,sceneItemLocked:m.locked,sceneItemTransform:{positionX:0,positionY:0,scaleX:1,scaleY:1,rotation:0}}],inputs:[{inputName:'Camera source'}],mixer:[{inputName:'Mic',inputVolumeDb:m.volume,inputMuted:m.muted}],stream:{outputActive:m.stream},record:{outputActive:m.record}};
 if(op==='preview')return {image:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aXioAAAAASUVORK5CYII='};return {connected:m.online};},request:async q=>{const res=await fetch(origin+q.route,{method:q.body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+q.token,'Content-Type':'application/json'},body:q.body===undefined?undefined:JSON.stringify(q.body)});const data=await res.json();if(!res.ok)throw Error(data.error);return data;}};
 },{origin});
 await page.goto(origin);await page.waitForFunction(()=>document.body.dataset.ready==='true');
 await page.locator('#setupName').fill('Alice');await page.locator('#setupNext').click();assert(await page.locator('#connectionsPanel').isVisible());await page.locator('#linkTwitch').click();assert(await page.locator('#twitchConnect').isVisible());await page.locator('#setupSkip').click();await page.locator('#obsMode').selectOption('auto');await page.locator('#obsPassword').fill('obs-pass');await page.locator('#obsConnect').click();await page.locator('#setupNext').click();await page.locator('#hostRelay').click();assert(await page.locator('#installerPending').isVisible());
 await page.locator('#serverNickname').fill('Local relay');await page.locator('#address').fill(origin);await page.locator('#address').locator('..').locator('button').click();assert.equal(await page.locator('#address').getAttribute('type'),'text');await page.locator('#password').fill(store.joinPassword);await page.locator('#connect').click();await page.waitForFunction(()=>document.querySelector('#serverStatus').textContent.startsWith('Connected'));await page.locator('#setupNext').click();assert(await page.locator('#studioPage').isVisible());
 await page.waitForFunction(()=>window.obsCalls.some(c=>c.op==='configure'));assert.equal(await page.locator('#obsApply').count(),0);
 await page.locator('#obsScenesPanel').waitFor({state:'visible'});await page.locator('#obsScenes').getByRole('button',{name:'Break',exact:true}).click();await page.waitForFunction(()=>window.mockOBS.current==='Break');
 await page.getByLabel('Show Camera source',{exact:true}).uncheck();await page.waitForFunction(()=>!window.mockOBS.shown);await page.getByLabel('Lock Camera source',{exact:true}).check();await page.waitForFunction(()=>window.mockOBS.locked);
 await page.locator('#obsSources').getByRole('button',{name:'Camera source',exact:true}).click();assert(await page.locator('#obsTransformSave').isDisabled());
 await page.locator('#obsMixer').getByRole('button',{name:'Mute',exact:true}).click();await page.waitForFunction(()=>window.mockOBS.muted);
 const configuredBefore=await page.evaluate(()=>window.obsCalls.filter(c=>c.op==='configure').length);await page.locator('#newStream').click();assert(await page.locator('#startStream').isDisabled());await page.waitForFunction(n=>window.obsCalls.filter(c=>c.op==='configure').length>n,configuredBefore);await page.evaluate(()=>window.dispatchEvent(new Event('stream-prepared')));await page.locator('#startStream').click();await page.waitForFunction(()=>window.mockOBS.stream);await page.locator('#stopOBSStream').click();await page.waitForFunction(()=>!window.mockOBS.stream);
 await page.waitForFunction(()=>document.querySelector('.obs-preview-image'));await page.locator('#settingsGear').click();assert(await page.locator('#generalSettings').isVisible());assert(!(await page.locator('#relaySetup').isVisible()));await page.locator('[data-setting=preview]').click();await page.locator('#obsPreviewEnabled').uncheck();await page.evaluate(()=>{document.querySelectorAll('dialog[open]').forEach(d=>d.close())});
 await page.waitForTimeout(200);const count=await page.evaluate(()=>window.obsCalls.filter(c=>c.op==='preview').length);await page.waitForTimeout(2200);assert.equal(await page.evaluate(()=>window.obsCalls.filter(c=>c.op==='preview').length),count);assert.equal(await page.locator('.obs-preview-image').count(),0);
 await page.locator('#settingsGear').click();await page.locator('[data-setting=obs]').click();const box=await page.locator('#obsRemember').boundingBox();assert(box.width<25&&box.height<25);await page.screenshot({path:path.resolve('UniversalCollab-rc7-settings-preview.png'),fullPage:true});await page.evaluate(()=>{document.querySelectorAll('dialog[open]').forEach(d=>d.close())});
 await page.locator('#collabButton').click();assert(await page.locator('#collabExplanation').isVisible());await page.locator('#acceptExplanation').click();await page.locator('#collabMembers').waitFor({state:'visible'});await page.locator('[data-close=collabMenu]').click();
 store.collabRequest('friend','Alice');await page.locator('#refresh').click();await page.waitForFunction(()=>document.querySelector('#collabCount').textContent==='+1');await page.locator('#collabButton').click();assert(!(await page.locator('#collabExplanation').isVisible()));await page.locator('#mutualPeople').getByRole('button',{name:'Accept',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#mutualPeople').textContent.includes('Collab active'));
 assert(store.allowed('friend','Alice','fallback'));store.collabRequest('friend','Alice',true);await page.waitForFunction(()=>document.querySelector('#mutualPeople').textContent.includes('Super Collab request —'));await page.locator('#mutualPeople').getByRole('button',{name:'Accept',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#mutualPeople').textContent.includes('Super Collab active'));await page.locator('[data-close=collabMenu]').click();
 await page.locator('#addItem').click();await page.locator('#itemChoices').getByRole('button',{name:'friend POV'}).click();assert.equal(await page.evaluate(()=>streamCanvas.snapshot().items.find(i=>i.publisher==='friend').x),.5);
 await page.locator('[data-item="video:friend"]').click({button:'right'});await page.locator('#itemContext').getByRole('button',{name:'Lock item',exact:true}).click();assert(await page.locator('#canvasWidth').isDisabled());await page.evaluate(()=>streamCanvas.toggleLock());await page.evaluate(()=>document.querySelector('#sourceProperties').show());await page.locator('#canvasWidth').fill('40');await page.locator('#canvasWidth').press('Tab');await page.evaluate(()=>streamCanvas.save());await page.waitForFunction(()=>!layoutDirty);assert.equal(store.get('Alice').settings.overlays[0].width,.4);await page.evaluate(()=>document.querySelector('#sourceProperties').close());
 await page.locator('#sceneName').fill('Together');await page.locator('#sceneDuplicate').click();await page.locator('#sceneList').getByRole('button',{name:'Together'}).click();await page.waitForFunction(()=>document.querySelector('#sceneList button[aria-pressed=true]').textContent==='Together');
 await page.evaluate(()=>document.querySelector('#workspaceDialog').show());await page.getByLabel('Chat column',{exact:true}).selectOption('dockLeft');await page.locator('[data-close=workspaceDialog]').click();assert.equal(await page.locator('#chatSurface').evaluate(n=>n.parentElement.id),'dockLeft');
 await page.locator('#settingsGear').click();await page.locator('[data-setting=relay]').click();await page.locator('#openAdminAccess').click();await page.locator('#hostClaimCode').fill(fs.readFileSync(directory+'/host-setup-code.txt','utf8').trim());await page.locator('#hostPanel').getByRole('button',{name:'Claim this relay',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#hostContent').textContent.includes('Free self-hosted'));assert(await page.locator('#adminPageWindow').isVisible());await page.evaluate(()=>{document.querySelectorAll('dialog[open]').forEach(d=>d.close())});

 // rc.7 workspace behavior: no navigation, layering, resolution and reconnect.
 await page.locator('#settingsGear').click();assert(await page.locator('#studioPage').isVisible());assert(await page.locator('#layoutPreview').isVisible());await page.locator('[data-setting=output]').click();assert(await page.locator('#fallbackPanel').isVisible());assert.equal(await page.locator('#fallbackPanel').evaluate(n=>n.closest('#settingsPage')?.id),'settingsPage');await page.locator('[data-close=settingsPageWindow]').click();
 await page.locator('[data-layer="video:friend"] .source-name').click();await page.getByRole('button',{name:'Hide friend POV',exact:true}).click();assert(!(await page.locator('[data-item="video:friend"]').isVisible()));await page.locator('#applyCanvas').click();await page.waitForFunction(()=>!layoutDirty);assert.equal(store.get('Alice').settings.overlays[0].visible,false);await page.getByRole('button',{name:'Show friend POV',exact:true}).click();
 await page.locator('[data-layer="main"]').dragTo(page.locator('[data-layer="video:friend"]'));await page.locator('#applyCanvas').click();await page.waitForFunction(()=>!layoutDirty);assert(store.get('Alice').settings.main.z>store.get('Alice').settings.overlays[0].z);assert.equal(await page.locator('#canvasLayers > :first-child').getAttribute('data-layer'),'main');
 await page.locator('#layoutResolution').selectOption('1080x1920');await page.locator('#applyResolution').click();await page.waitForFunction(()=>!layoutDirty);assert.deepEqual(store.get('Alice').settings.resolution,{width:1080,height:1920});assert.equal(await page.locator('#layoutPreview').evaluate(n=>n.style.aspectRatio),'1080 / 1920');await page.locator('#layoutResolution').selectOption('1920x1080');await page.locator('#applyResolution').click();await page.waitForFunction(()=>!layoutDirty);
 await page.locator('#settingsGear').click();await page.locator('[data-setting=obs]').click();assert(await page.locator('#obsAutoReconnect').isChecked());await page.evaluate(()=>mockOBS.online=false);await page.waitForFunction(()=>obsCalls.some(c=>c.op==='connect'&&c.input.retry),null,{timeout:7000});await page.locator('#obsDisconnect').click();const attempts=await page.evaluate(()=>obsCalls.filter(c=>c.op==='connect').length);await page.waitForTimeout(4200);assert.equal(await page.evaluate(()=>obsCalls.filter(c=>c.op==='connect').length),attempts);await page.locator('#obsConnect').click();await page.locator('[data-setting=preview]').click();await page.locator('#obsPreviewRate').selectOption('100');await page.locator('#obsPreviewEnabled').check();await page.locator('[data-close=settingsPageWindow]').click();await page.waitForFunction(()=>document.querySelector('.obs-preview-image'));await page.locator('#settingsGear').click();await page.locator('[data-setting=preview]').click();const shots=await page.evaluate(()=>obsCalls.filter(c=>c.op==='preview').length);await page.waitForTimeout(600);assert(await page.evaluate(()=>obsCalls.filter(c=>c.op==='preview').length)>shots);await page.locator('[data-close=settingsPageWindow]').click();
 assert(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight&&document.documentElement.scrollWidth<=innerWidth));
 await page.locator('#scenePanel .dock-handle').dragTo(page.locator('#dockBottom'));assert.equal(await page.locator('#scenePanel').evaluate(n=>n.parentElement.id),'dockBottom');
 await page.evaluate(()=>document.querySelector('#workspaceReset').click());
 await page.locator('.app-menu').filter({has:page.locator('summary', {hasText:'File'})}).locator('summary').click();assert.equal(await page.locator('.app-menu[open]').getByRole('menuitem',{name:'New Stream',exact:true}).count(),0);await page.locator('#menuBar').click({position:{x:800,y:20}});
 console.log('PASS rc7 persistent dialogs, four docks, actual title drag, source visibility and z order saved to relay, resolution, two-second reconnect and explicit pause, faster preview continues under Settings, no document scrollbars.');
 console.log(await page.evaluate(()=>{const c=document.querySelector('#layoutPreview'),p=c.parentElement;return {parent:p.tagName,height:p.clientHeight,children:[...p.children].map(n=>[n.id,n.offsetHeight,getComputedStyle(n).marginTop,getComputedStyle(n).marginBottom])}}));await page.screenshot({path:path.resolve('UniversalCollab-rc7-connected-preview.png'),fullPage:true});
 await page.reload();await page.waitForFunction(()=>document.body.dataset.ready==='true');assert(!(await page.locator('#setupGuide').isVisible()));await page.locator('#settingsGear').click();await page.locator('[data-setting=relay]').click();await page.locator('#serverConnect').click();await page.waitForFunction(()=>connected);await page.evaluate(()=>{document.querySelectorAll('dialog[open]').forEach(d=>d.close())});assert.equal(await page.locator('#sceneList button[aria-pressed=true]').textContent(),'Together');assert.equal(await page.locator('#chatSurface').evaluate(n=>n.parentElement.id),'dockRight');
 await page.screenshot({path:path.resolve('UniversalCollab-rc7-studio-preview.png'),fullPage:true});await page.setViewportSize({width:600,height:950});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));assert.deepEqual(errors,[]);
 console.log('PASS fresh startup; four-step onboarding; stable platform/server/OBS controls; saved login reconnect; one-time warning; mutual + persistent Collab; centered/locked items; scene persistence; panel customization; owner admin; mobile width.');
}finally{await browser?.close();await new Promise(r=>server?server.server.close(r):r());fs.rmSync(directory,{recursive:true,force:true});}
