(()=>{
 const make=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;};
 const root=make('details');root.id='hostPanel';root.className='card';root.append(make('summary','Relay host administration'));const intro=make('p','Own this relay? Claim it once using the private setup code from data/host-setup-code.txt. Sign in first if your member account already exists.');root.append(intro);
 const feedback=make('p');feedback.id='hostFeedback';feedback.setAttribute('role','status');root.append(feedback);
 const claim=make('form');const code=make('input');code.type='password';code.autocomplete='off';code.id='hostClaimCode';const cl=make('label','One-time host setup code');cl.append(code);const cb=make('button','Claim this relay');cb.type='submit';claim.append(cl,cb);root.append(claim);
 const refreshButton=button('Load host controls',()=>load());refreshButton.id='hostLoad';root.append(refreshButton);const content=make('div');content.id='hostContent';root.append(content);$('adminPage').append(root);root.open=true;
 let identity='',working=false;
 const currentIdentity=()=>profile?profile.address+'|'+profile.id+'|'+profile.token:'';
 const tell=e=>{feedback.textContent=e?.message||String(e);};
 async function run(fn){if(working)return;working=true;root.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){tell(e);}finally{working=false;root.querySelectorAll('button').forEach(b=>b.disabled=false);}}
 claim.onsubmit=e=>{e.preventDefault();run(async()=>{if(!(await verifyIdle()))throw Error('End streaming before claiming a relay.');const setupCode=code.value;code.value='';if(!connected){profile={address:desktop?address($('address').value.trim()):location.origin,id:$('username').value.trim(),token:''};}const result=await api('/api/v3/host-claim',{code:setupCode,username:profile.id});profile.id=result.id;profile.token=result.token;await saveProfile();await enter();await load();});};
 async function load(){if(!connected){tell('Connect or claim the relay first.');return;}const expected=currentIdentity();try{const result=await api('/api/v3/host-view');if(expected!==currentIdentity()||!connected||uncertain)return;identity=expected;paint(result);tell('Host controls loaded.');}catch(e){content.replaceChildren();tell(e);}}
 async function mutate(route,body){const expected=currentIdentity();if(identity!==expected)throw Error('Load controls for the selected server first.');const result=await api('/api/v3/host-'+route,body);if(expected===currentIdentity()){paint(result);await refresh();tell('Saved.');}}
 function field(form,label,id,value,type='number'){const l=make('label',label),i=make('input');i.id=id;i.type=type;i.value=value;i.autocomplete='off';l.append(i);form.append(l);return i;}
 function paint(v){content.replaceChildren();claim.hidden=true;const summary=make('section');summary.append(make('h3','Free self-hosted server'),make('p',`${v.counts.members}/${v.policy.memberLimit} members · ${v.counts.guests}/${v.policy.guestLimit} guests`));
 summary.append(button('Sign out other owner devices',()=>{if(confirm('Rotate your owner login? Other devices will need the new personal token. OBS keys stay unchanged.'))run(async()=>{const expected=currentIdentity();const result=await api('/api/v3/host-rotate',{});if(expected!==currentIdentity())throw Error('Server selection changed.');profile.token=result.token;await saveProfile();await load();});}));content.append(summary);
 const settings=make('form');settings.append(make('h3','Server limits'));const fields={};for(const[k,label,value]of[['memberLimit','Member slots',v.policy.memberLimit],['maxSessions','Simultaneous broadcasts (hardware limit)',v.maxSessions],['guestLimit','Guest slots',v.policy.guestLimit],['guestMaxMinutes','Maximum guest minutes',v.policy.guestMaxMinutes],['defaultStorageMB','Default recording quota per member (MiB)',v.policy.defaultStorageMB],['maxStorageMB','Total recording storage (MiB)',v.policy.maxStorageMB??1024],['minFreeMB','Keep disk space free (MiB)',v.policy.minFreeMB??256]])fields[k]=field(settings,label,'host-'+k,value);
 const toggles={};for(const k of ['registration','guestInvites','recording','recordingManagement','pictureInPicture','collaboratorFallback','chatOverlays','multipleDestinations','manualFallback','fallbackTimeout','povLabels','streamHealth','sessionPermissions']){const l=make('label',({registration:'Allow new members with the join password',guestInvites:'Allow host guest invitations',recording:'Allow recording',recordingManagement:'Allow members to delete their recordings',pictureInPicture:'Allow picture in picture',collaboratorFallback:'Allow collaborator fallback',chatOverlays:'Allow chat overlays',multipleDestinations:'Allow multiple destinations',manualFallback:'Allow manual fallback',fallbackTimeout:'Allow disconnect timeout',povLabels:'Allow POV labels',streamHealth:'Allow stream health checks',sessionPermissions:'Allow session-only approvals'})[k]);const i=make('input');i.type='checkbox';i.checked=!!v.features[k];i.id='host-feature-'+k;toggles[k]=i;l.prepend(i);settings.append(l);}const save=make('button','Save server settings');save.type='submit';settings.append(save,make('p','Storage limits stop recording without deleting files. Lower broadcast limits apply to new sessions.'));settings.onsubmit=e=>{e.preventDefault();run(()=>mutate('settings',{...Object.fromEntries(Object.entries(fields).map(([k,i])=>[k,Number(i.value)])),features:Object.fromEntries(Object.entries(toggles).map(([k,i])=>[k,i.checked]))}));};content.append(settings);
 content.append(make('h3','Members and guests'));for(const u of v.members){const row=make('section');row.className='card';row.append(make('h4',u.id+' · '+u.role+(u.disabled?' · access removed':'')),make('p',`${u.usedMB.toFixed(1)} MiB stored · ${u.canStart?'May start broadcasting':'New broadcasting unavailable'}`));if(u.guestExpiresAt)row.append(make('p','Guest expiry: '+new Date(u.guestExpiresAt).toLocaleString()));const quota=field(row,'Recording quota (MiB; 0 disables recording)','quota-'+u.id,u.storageLimitMB);row.append(button('Save quota',()=>run(()=>mutate('member',{id:u.id,storageLimitMB:Number(quota.value)}))));
 if(u.role!=='owner'){row.append(button(u.disabled?'Restore access':'Remove access',()=>{if(confirm((u.disabled?'Restore access for ':'Disconnect and remove access for ')+u.id+'? Recordings will be retained.'))run(()=>mutate('member',{id:u.id,disabled:!u.disabled}));}));row.append(button(u.role==='guest'?'Make member':'Make temporary guest',()=>{if(confirm('Change '+u.id+' to '+(u.role==='guest'?'a member':'a temporary guest')+'?'))run(()=>mutate('member',{id:u.id,role:u.role==='guest'?'member':'guest',minutes:v.policy.guestMaxMinutes}));}));}
 row.append(button('End broadcast',()=>{if(confirm('End '+u.id+'’s broadcast now?'))run(()=>mutate('action',{id:u.id,action:'end'}));}));row.append(button('Allow broadcasting again',()=>{if(confirm('Allow '+u.id+' to broadcast again?'))run(()=>mutate('action',{id:u.id,action:'allow'}));}));content.append(row);}
 const invites=make('section');invites.append(make('h3','Guest invitations'));const guestMinutes=field(invites,'Guest duration (minutes)','hostGuestMinutes',v.policy.guestMaxMinutes);const inviteSecret=field(invites,'Private invitation link','hostGuestLink','','password');inviteSecret.readOnly=true;invites.append(button('Create guest invitation',()=>run(async()=>{const result=await api('/api/v3/invite',{minutes:Number(guestMinutes.value)});inviteSecret.value=profile.address+'/#invite='+encodeURIComponent(result.secret);tell('Invitation created. Copy it privately.');})),button('Copy guest invitation',()=>copyValue(inviteSecret.value)));for(const i of v.invites){const p=make('p',(i.usedBy||'Unused')+' · '+(i.revoked?'revoked':new Date(i.expiresAt).toLocaleString()));if(!i.revoked&&i.expiresAt>Date.now())p.append(button('Revoke invitation',()=>run(async()=>{await api('/api/v3/invite-revoke',{id:i.id});await load();})));invites.append(p);}content.append(invites,make('h3','Recent administration activity'));for(const a of v.audit.slice().reverse())content.append(make('p',new Date(a.at).toLocaleString()+' · '+a.actor+' · '+a.event+' '+a.target));
 }
 setInterval(()=>{if(identity&&(!connected||uncertain||identity!==currentIdentity()||!view?.me?.isHost)){identity='';content.replaceChildren();feedback.textContent='Load controls for the selected server.';}claim.hidden=!!(connected&&view?.me?.isHost);refreshButton.hidden=!connected;},1000);
})();
