'use strict';
(async()=>{
 await window.portalReady;
 if(document.body.dataset.ready!=='true')await new Promise(r=>window.addEventListener('studio-ready',r,{once:true}));
 const $=id=>document.getElementById(id),bridge=window.relayDesktop;
 const node=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;};
 const btn=(text,fn)=>{const n=node('button',text);n.type='button';n.onclick=()=>run(fn);return n;};
 const status=node('p');status.id='obsControlStatus';status.setAttribute('role','status');$('streamsPanel').append(status);
 const previewStatus=node('p','OBS preview off — connect OBS to display its output.');previewStatus.id='obsPreviewStatus';previewStatus.className='hint';$('layoutPreview').after(previewStatus);
 let retrying=false,autoRetry=localStorage.getItem('uc-ui7-obs-retry')!=='false',paired=localStorage.getItem('uc-ui7-obs-paired')==='true',retryPaused=false;
 let draftPending=false,state=null,online=false,polling=false,working=false,editScene='',selectedSource=null,signature='',lastAuto='',configuring=null,previewBusy=false,previewTimer,previewEpoch=0,meters=false;
 let pref;try{pref=JSON.parse(localStorage.getItem('uc-ui6-preview'));}catch{}pref={enabled:pref?.enabled!==false,rate:[100,200,500,1000,2000].includes(pref?.rate)?pref.rate:200,width:[320,640,1280].includes(pref?.width)?pref.width:640};
 const say=text=>{status.textContent=text;$('obsFeedback').textContent=text;};
 const call=(op,input={})=>{if(!bridge?.obs)throw Error('OBS controls require the desktop app.');return bridge.obs(op,{...input,serverKey:selected()?.key});};
 async function run(fn){if(working)return;working=true;buttons();try{await fn();}catch(e){say(e.message);}finally{working=false;buttons();}}
 const start=btn('Start Stream',async()=>{if(!online)throw Error('Connect OBS in Settings → OBS first.');await call('start',{automatic:$('obsMode').value==='auto'});say('Stream started in OBS.');await poll();});start.id='startStream';$('newStream').after(start);
 const stop=btn('Stop Stream',async()=>{if(confirm('Stop sending your OBS feed? Your relay may continue broadcasting its fallback until you end the relay broadcast.')){await call('stream-stop');say('OBS stream stopped.');await poll();}});stop.id='stopOBSStream';start.after(stop);
 const record=btn('Start Recording',async()=>{if(state?.record?.outputActive){if(!confirm('Stop the local OBS recording?'))return;await call('record-stop');}else await call('record-start');await poll();});record.id='obsRecord';stop.after(record);
 function buttons(){start.hidden=!!state?.stream?.outputActive;stop.hidden=!online||!state?.stream?.outputActive;record.hidden=!online;start.disabled=draftPending||working||!online||!connected||uncertain||!!state?.stream?.outputActive;stop.disabled=working||!state?.stream?.outputActive;record.disabled=working||!online;record.textContent=state?.record?.outputActive?'Stop Recording':'Start Recording';}
 function connection(value){$('obsConnectionIndicator').textContent=value?'OBS: Connected':retryPaused?'OBS: Disconnected':paired&&autoRetry?'OBS: Reconnecting':'OBS: Disconnected';const changed=online!==value;online=value;window.obsConnected=value;if(!value){state=null;lastAuto='';editScene='';signature='';previewEpoch++;clearTimeout(previewTimer);window.streamCanvas.preview('');previewStatus.textContent='OBS preview unavailable — OBS is disconnected.';$('obsVideoFields').hidden=true;$('obsSettingsState').textContent='Connect OBS to edit these settings.';}buttons();if(changed){window.dispatchEvent(new Event('obs-connection'));if(value){schedulePreview();void autoConfigure();}}}
 async function autoConfigure(force=false){if(!online||!connected||uncertain||$('obsMode').value!=='auto')return;const key=selected()?.key;if(!key||(!force&&lastAuto===key))return;if(configuring)return configuring;lastAuto=key;configuring=(async()=>{try{await call('configure');say('Relay URL and key set and verified in OBS.');}catch(e){say(e.message+' New Stream or Start Stream will retry when ready.');}finally{configuring=null;}})();return configuring;}
 async function connect(saved,discover=false){const password=$('obsPassword').value;$('obsPassword').value='';await call('connect',discover?{discover:true}:saved?{saved:true}:{port:Number($('obsPort').value),password,remember:$('obsRemember').checked});paired=true;retryPaused=false;localStorage.setItem('uc-ui7-obs-paired','true');connection(true);say('OBS connected.');await autoConfigure();await poll();await loadSettings();}
 window.connectOBSAutomatically=()=>connect(false,true);
 $('obsConnect').onclick=()=>run(()=>connect(false));$('obsReconnect').onclick=()=>run(()=>connect(true));
 $('obsDisconnect').onclick=()=>run(async()=>{retryPaused=true;await call('disconnect');connection(false);say('OBS disconnected.');});
 $('obsRestore').onclick=()=>run(async()=>{if(confirm('Restore the OBS destination from before automatic relay setup? Stop OBS streaming first. Automatic mode will change it again when you connect to a relay or prepare a stream.')){await call('restore');say('Previous OBS destination restored.');}});
 $('obsMode').addEventListener('change',()=>{if($('obsMode').value==='auto')void autoConfigure(true);});
 $('newStream').addEventListener('click',()=>{draftPending=true;buttons();void autoConfigure(true);});window.addEventListener('stream-prepared',()=>{draftPending=false;buttons();void autoConfigure(true);});
 window.addEventListener('relay-state',()=>{buttons();if(!connected)lastAuto='';void autoConfigure();});
 function optionList(select,list,value){const before=JSON.stringify([...select.options].map(o=>[o.value,o.textContent]));if(before!==JSON.stringify(list)){select.replaceChildren(...list.map(([v,n])=>new Option(n,v)));}select.value=value;}
 function transform(){const item=state?.items?.find(i=>i.sceneItemId===selectedSource);$('obsTransform').hidden=!item;if(!item)return;const t=item.sceneItemTransform||{};for(const[id,k,fallback]of[['obsSourceX','positionX',0],['obsSourceY','positionY',0],['obsSourceSX','scaleX',1],['obsSourceSY','scaleY',1],['obsSourceRotation','rotation',0]]){if(document.activeElement!==$(id))$(id).value=t[k]??fallback;$(id).disabled=!!item.sceneItemLocked;}$('obsTransformSave').disabled=!!item.sceneItemLocked;}
 function paint(){
  buttons();const scenes=(state.scenes||[]).map(s=>[s.sceneName,s.sceneName]);optionList($('obsEditScene'),scenes,editScene);
  const sceneSig=JSON.stringify([scenes,state.current]);if($('obsScenes').dataset.signature!==sceneSig){$('obsScenes').dataset.signature=sceneSig;$('obsScenes').replaceChildren(...scenes.map(([name])=>{const b=btn(name,async()=>{await call('scene-switch',{sceneName:name});editScene=name;selectedSource=null;await poll();});b.setAttribute('aria-pressed',String(name===state.current));return b;}));}
  const items=state.items||[];const next=JSON.stringify([editScene,items]);
  if(next!==signature&&!$('obsSources').contains(document.activeElement)){signature=next;$('obsSources').replaceChildren();for(const item of [...items].sort((a,b)=>b.sceneItemIndex-a.sceneItemIndex)){
   const row=node('div');row.className='obs-source-row';const base={sceneName:editScene,id:item.sceneItemId};
   const select=btn(item.sourceName,()=>{selectedSource=item.sceneItemId;transform();});select.className='source-name';row.append(select);
   const toggle=(label,checked,op,key)=>{const l=node('label',label),c=node('input');c.type='checkbox';c.checked=checked;c.setAttribute('aria-label',label+' '+item.sourceName);c.onchange=()=>run(async()=>{await call(op,{...base,[key]:c.checked});await poll();});l.className='check-row';l.prepend(c);row.append(l);};
   toggle('Show',item.sceneItemEnabled,'source-visible','enabled');toggle('Lock',item.sceneItemLocked,'source-lock','locked');
   for(const[text,delta]of[['↑',1],['↓',-1]]){const b=btn(text,async()=>{await call('source-order',{...base,index:item.sceneItemIndex+delta});await poll();});b.setAttribute('aria-label',(delta===1?'Raise ':'Lower ')+item.sourceName);b.disabled=item.sceneItemIndex+delta<0||item.sceneItemIndex+delta>=items.length;row.append(b);}
   row.append(btn('Remove',async()=>{if(confirm('Remove '+item.sourceName+' from this OBS scene?')){await call('source-delete',base);selectedSource=null;await poll();}}));$('obsSources').append(row);
  }}
  optionList($('obsExistingSource'),(state.inputs||[]).map(i=>[i.inputName,i.inputName]),$('obsExistingSource').value||(state.inputs||[])[0]?.inputName||'');
  const mixer=$('obsMixer'),names=(state.mixer||[]).map(i=>i.inputName);if(mixer.dataset.names!==JSON.stringify(names)){mixer.dataset.names=JSON.stringify(names);mixer.replaceChildren();for(const input of state.mixer||[]){const row=node('div');row.className='obs-mixer-row';row.dataset.name=input.inputName;row.append(node('strong',input.inputName));const meter=node('meter');meter.min=0;meter.max=1;meter.value=0;meter.setAttribute('aria-label',input.inputName+' audio level');const slider=node('input');slider.type='range';slider.min=-100;slider.max=0;slider.step=1;slider.setAttribute('aria-label',input.inputName+' volume');slider.onchange=()=>run(async()=>{await call('volume',{inputName:input.inputName,db:Number(slider.value)});await poll();});const mute=btn('Mute',async()=>{const latest=state.mixer.find(i=>i.inputName===input.inputName);await call('mute',{inputName:input.inputName,muted:!latest.inputMuted});await poll();});row.append(meter,slider,mute);mixer.append(row);}}
  for(const row of mixer.children){const input=state.mixer.find(i=>i.inputName===row.dataset.name),slider=row.querySelector('input'),mute=row.querySelector('button');if(document.activeElement!==slider)slider.value=Number.isFinite(input.inputVolumeDb)?Math.max(-100,input.inputVolumeDb):-100;mute.textContent=input.inputMuted?'Unmute':'Mute';mute.setAttribute('aria-pressed',String(input.inputMuted));}
  transform();
 }
 async function poll(){if(polling||!bridge?.obs||document.hidden)return;polling=true;try{const r=await call('state');connection(!!r.connected);if(online){if(!$('studioPage').hidden){state=await call('snapshot',{...(editScene?{sceneName:editScene}:{})});editScene=state.sceneName;paint();}else buttons();}}catch(e){say(e.message);editScene='';}finally{polling=false;updateMeters();}}
 function updateMeters(){const next=online&&!document.hidden&&!$('studioPage').hidden&&!$('obsMixerPanel').hidden;if(next===meters)return;meters=next;if(online)call('meters',{enabled:next}).catch(()=>{});}
 $('obsEditScene').onchange=()=>run(async()=>{editScene=$('obsEditScene').value;selectedSource=null;await poll();});
 for(const[button,op]of[['obsSceneCreate','scene-create'],['obsSceneRename','scene-rename'],['obsSceneDelete','scene-delete']])$(button).onclick=()=>run(async()=>{const name=$('obsSceneName').value.trim();if(op==='scene-delete'&&!confirm('Delete the OBS scene “'+editScene+'” and its scene items?'))return;await call(op,{sceneName:op==='scene-create'?name:editScene,newName:name});editScene=op==='scene-delete'?'':name;selectedSource=null;await poll();});
 $('obsSourceAdd').onclick=()=>run(async()=>{await call('source-add',{sceneName:editScene,sourceName:$('obsExistingSource').value});await poll();});
 $('obsTransformSave').onclick=()=>run(async()=>{await call('source-transform',{sceneName:editScene,id:selectedSource,x:Number($('obsSourceX').value),y:Number($('obsSourceY').value),scaleX:Number($('obsSourceSX').value),scaleY:Number($('obsSourceSY').value),rotation:Number($('obsSourceRotation').value)});await poll();});
 const videoMap={baseWidth:'obsBaseWidth',baseHeight:'obsBaseHeight',outputWidth:'obsOutputWidth',outputHeight:'obsOutputHeight',fpsNumerator:'obsFPSNum',fpsDenominator:'obsFPSDen'};
 async function loadSettings(){if(!online)return;const s=await call('settings');for(const[k,id]of Object.entries(videoMap))$(id).value=s.video[k];$('obsRecordDirectory').value=s.record?.recordDirectory||'';$('obsRecordDirectorySave').disabled=!s.record;$('obsVideoFields').hidden=false;$('obsSettingsState').textContent='Connected to OBS. Changes apply to its current profile.';}
 $('obsSettingsLoad').onclick=()=>run(loadSettings);$('obsVideoSave').onclick=()=>run(async()=>{await call('video',Object.fromEntries(Object.entries(videoMap).map(([k,id])=>[k,Number($(id).value)])));await loadSettings();say('OBS video settings saved.');});$('obsRecordDirectorySave').onclick=()=>run(async()=>{await call('record-directory',{directory:$('obsRecordDirectory').value});say('OBS recording folder saved.');});
 $('obsPreviewEnabled').checked=pref.enabled;$('obsPreviewRate').value=String(pref.rate);$('obsPreviewWidth').value=String(pref.width);
 function previewAllowed(){return pref.enabled&&online&&!document.hidden&&!$('studioPage').hidden&&!$('canvasPanel').hidden;}
 function schedulePreview(){clearTimeout(previewTimer);previewTimer=null;if(!pref.enabled){window.streamCanvas.preview('');previewStatus.textContent='OBS preview is off.';return;}if(!previewAllowed())return;previewTimer=setTimeout(preview,pref.rate);}
 async function preview(){previewTimer=null;if(previewBusy||!previewAllowed())return;previewBusy=true;const epoch=previewEpoch;try{const r=await call('preview',{width:pref.width});if(epoch===previewEpoch&&previewAllowed()){window.streamCanvas.preview(r.image);previewStatus.textContent='OBS program preview · '+(1000/pref.rate)+' fps · local image';}}catch(e){window.streamCanvas.preview('');previewStatus.textContent='OBS preview unavailable: '+e.message;}finally{previewBusy=false;schedulePreview();}}
 for(const id of ['obsPreviewEnabled','obsPreviewRate','obsPreviewWidth'])$(id).onchange=()=>{pref={enabled:$('obsPreviewEnabled').checked,rate:Number($('obsPreviewRate').value),width:Number($('obsPreviewWidth').value)};localStorage.setItem('uc-ui6-preview',JSON.stringify(pref));previewEpoch++;schedulePreview();};
 document.addEventListener('visibilitychange',()=>{previewEpoch++;schedulePreview();updateMeters();if(!document.hidden)void poll();});
 for(const b of document.querySelectorAll('[data-page]'))b.addEventListener('click',()=>{previewEpoch++;schedulePreview();updateMeters();void poll();});
 bridge?.onOBS?.(e=>{if(e.type==='connection'){connection(e.connected);if(!e.connected)say('OBS disconnected. Reconnect in Settings → OBS.');}else if(e.type==='meters'&&meters){for(const row of $('obsMixer').children){const input=e.inputs.find(i=>i.name===row.dataset.name);row.querySelector('meter').value=Math.min(1,Math.max(0,input?.level||0));}}});
 window.addEventListener('beforeunload',()=>{clearTimeout(previewTimer);if(online)call('meters',{enabled:false}).catch(()=>{});});
 $('obsAutoReconnect').checked=autoRetry;
 $('obsAutoReconnect').onchange=()=>{autoRetry=$('obsAutoReconnect').checked;retryPaused=false;localStorage.setItem('uc-ui7-obs-retry',String(autoRetry));connection(online);};
 async function retry(){if(!bridge?.obs||online||retrying||working||!paired||!autoRetry||retryPaused)return;retrying=true;try{await call('connect',{retry:true});connection(true);say('OBS reconnected.');await poll();}catch{connection(false);}finally{retrying=false;}}
 setInterval(()=>{void retry();},2000);
 setInterval(()=>{void poll();if(previewAllowed()&&!previewBusy&&!previewTimer)schedulePreview();},2000);
 buttons();await poll();schedulePreview();
})().catch(e=>{const p=document.getElementById('obsFeedback');if(p)p.textContent='OBS controls unavailable: '+e.message;});
