'use strict';
(()=>{
 const available=key=>view?.capabilities?.[key]===true;
 const make=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;};
 const layout=$('canvasSave').parentElement,options=make('div');options.className='row';const timeout=make('input');timeout.id='fallbackTimeout';timeout.type='number';timeout.min='0';timeout.max='1440';timeout.step='0.5';timeout.value='0';const timeoutLabel=make('label','Stop after primary disconnects (minutes; 0 = manual)');timeoutLabel.append(timeout);const labels=make('input');labels.id='povLabels';labels.type='checkbox';labels.checked=true;const label=make('label',' Show POV names');label.prepend(labels);options.append(timeoutLabel,label);layout.append(options);
 timeout.onchange=labels.onchange=()=>{layoutDirty=true;};
 const force=button('Show fallback now',()=>change('/api/'+(view?.status?.forcedFallback?'restore-primary':'force-fallback')));force.id='forceFallback';$('collab').after(force);
 const health=make('div');health.id='healthDashboard';health.setAttribute('role','status');$('destinationHealth').after(health);
 const check=button('Check stream readiness',async()=>{if(!connected)return;await refresh();const lines=[];lines.push(view?.me?.destinationConfigured?'Destination plan saved':'Prepare a stream first');lines.push(view?.status?.mode==='test'?'Server is in TEST mode: nothing goes to platforms':'Server is in LIVE mode');if(view?.status?.held)lines.push('Stop OBS reconnecting and wait for rearm');lines.push('OBS must use H.264 video, AAC audio and the permanent key shown in OBS connection.');note(lines.join(' · '));});check.id='readinessCheck';$('newStream').after(check);
 const guests=make('details');guests.id='guestInvites';guests.append(make('summary','Guest invitations'));const explanation=make('p','Single-use invitation. The guest account expires with the invitation; the host must enable this feature.');const minutes=make('input');minutes.id='guestMinutes';minutes.type='number';minutes.min='5';minutes.max='1440';minutes.value='120';minutes.setAttribute('aria-label','Guest access minutes');const secret=make('input');secret.id='guestInviteLink';secret.type='password';secret.readOnly=true;secret.dataset.secret='true';secret.setAttribute('aria-label','Private guest invitation link');const list=make('div');list.id='guestInviteList';
 async function guestList(){if(!connected||!available('guestInvites'))return;try{const result=await api('/api/v3/invites');list.replaceChildren();for(const i of result.items){const row=make('p',(i.usedBy||'Unused invitation')+' · '+(i.revoked?'revoked':new Date(i.expiresAt).toLocaleString()));if(!i.revoked&&i.expiresAt>Date.now())row.append(button('Revoke',async()=>{await change('/api/v3/invite-revoke',{id:i.id});await guestList();}));list.append(row);}}catch(e){note(e.message);}}
 const create=button('Create guest invitation',async()=>{try{const result=await api('/api/v3/invite',{minutes:Number(minutes.value)});secret.value=profile.address+'/#invite='+encodeURIComponent(result.secret);note('Invitation created. Copy the private link to your guest.');await guestList();}catch(e){note(e.message);}});create.id='createGuestInvite';const copy=button('Copy invitation',()=>{if(secret.value)copyValue(secret.value);});copy.id='copyGuestInvite';const load=button('Refresh invitations',guestList);guests.append(explanation,minutes,create,secret,copy,load,list);$('requests').after(guests);
 $('password').addEventListener('input',()=>{try{const u=new URL($('password').value);if(!['http:','https:'].includes(u.protocol))return;const invite=new URLSearchParams(u.hash.slice(1)).get('invite');if(!invite||!/^[A-Za-z0-9_-]{24,64}$/.test(invite))return;mode(true);$('password').value=invite;if(desktop)$('address').value=u.origin;note('Invitation loaded. Choose a new server username and connect.');}catch{}});
 if(!desktop&&location.hash.startsWith('#invite=')){const value=new URLSearchParams(location.hash.slice(1)).get('invite');if(value&&/^[A-Za-z0-9_-]{24,64}$/.test(value)){mode(true);$('password').value=value;history.replaceState(null,'',location.pathname);note('Guest invitation loaded. Choose a username.');}}
 const backups=make('details');backups.id='backupPanel';backups.append(make('summary','Encrypted settings backup'));const text=make('p','Includes saved server logins, platform logins and app settings. Use a private password of at least 12 characters. Restore replaces this device’s settings.');const pass=make('input');pass.id='backupPassword';pass.type='password';pass.autocomplete='new-password';pass.placeholder='Backup password';pass.dataset.secret='true';pass.setAttribute('aria-label','Backup password');
 const workspaceKeys=['uc-ui7-workspace','uc-ui7-dock-sizes','uc-ui7-obs-retry','uc-ui7-obs-paired','uc-ui6-preview','uc-ui5-setup','uc-ui5-scenes','uc-ui5-workspace','uc-ui5-workspace-presets','uc-ui5-obs-mode','uc-ui5-collab-explained','universalcollab-panel-groups-v2','universalcollab-workspace-v1','universalcollab-app-presets-v1','universalcollab-stream-presets-v1','universalcollab-chat-ui-v1','universalcollab-tools-v1'];
 async function backup(op){if(!desktop?.backup){note('Backups require the desktop app.');return;}if(active||uncertain||busy){note('End streaming before restoring or backing up settings.');return;}const password=pass.value;pass.value='';try{const workspace=Object.fromEntries(workspaceKeys.filter(k=>localStorage.getItem(k)!==null).map(k=>[k,localStorage.getItem(k)]));const result=await desktop.backup(op,{password,workspace});if(result.cancelled)return;if(result.restored){for(const key of workspaceKeys){if(result.workspace[key]!==undefined)localStorage.setItem(key,result.workspace[key]);else localStorage.removeItem(key);}localStorage.removeItem('universalcollab-production-draft-v1');location.reload();}else note('Encrypted backup saved.');}catch(e){note(e.message);}}
 backups.append(text,pass,button('Export encrypted backup',()=>backup('export')),button('Restore backup',()=>backup('import')));$('workspaceTools').append(backups);
 let lastServer='';function render(){const s=view?.status;check.disabled=!connected;force.disabled=!connected||!s?.broadcast||!available('manualFallback');force.textContent=s?.forcedFallback?'Return to my feed':'Show fallback now';timeout.disabled=!connected||!available('fallbackTimeout');labels.disabled=!connected||!available('povLabels');if(!layoutDirty&&connected){timeout.value=view.me.settings.fallbackTimeoutMinutes||0;labels.checked=view.me.settings.povLabels!==false;}health.replaceChildren();if(connected&&s?.health){const h=s.health;health.append(make('p','Primary: '+(h.inputHealthy?'receiving':'disconnected')+' · Output: '+(h.outputFps?Number(h.outputFps).toFixed(1)+' fps':'measuring')+' · Source: '+(h.sourceName||'reconnect image')+' · Uptime: '+Math.floor(h.uptimeSeconds/60)+' min'));if(Number.isFinite(s.fallbackRemainingSeconds))health.append(make('p','Auto-end in '+s.fallbackRemainingSeconds+' seconds unless your primary returns.'));}create.disabled=load.disabled=!connected||!available('guestInvites')||!!view?.me?.guestExpiresAt||(view?.capabilities?.hostAdmin===1&&!view?.me?.isHost);const key=connected?selected()?.key:'';if(key!==lastServer){lastServer=key;secret.value='';list.replaceChildren();}if(connected&&view.me.canStart===false)health.append(make('p','New broadcasts unavailable: ask the host to check your access and available member or guest slots.'));if(connected&&view.me.guestExpiresAt)health.append(make('p','Guest access expires '+new Date(view.me.guestExpiresAt).toLocaleString()));}
 window.releaseFeatures={render,settings:()=>({fallbackTimeoutMinutes:Number(timeout.value),povLabels:labels.checked})};render();
})();
