'use strict';
(async()=>{
 await window.portalReady;if(!window.workspaceUI)await new Promise(r=>window.addEventListener('studio-ready',r,{once:true}));
 const $=id=>document.getElementById(id),ui=window.workspaceUI;
 const make=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;};
 const button=(text,fn)=>{const b=make('button',text);b.type='button';b.onclick=fn;return b;};
 let z=80;
 function floating(dialog){if(dialog.dataset.floating)return;dialog.dataset.floating='true';dialog.classList.add('floating-window');let title=dialog.querySelector(':scope > .window-title');if(!title){title=make('div');title.className='window-title';title.append(make('strong',dialog.querySelector('h2')?.textContent||'Tools'),button('×',()=>dialog.close()));dialog.prepend(title);}let drag;
 title.onpointerdown=e=>{if(e.button!==0||e.target.closest('button')||(window.onboardingActive&&dialog.id==='settingsPageWindow'))return;const r=dialog.getBoundingClientRect();drag={x:e.clientX,y:e.clientY,left:r.left,top:r.top};title.setPointerCapture(e.pointerId);e.preventDefault();};title.onpointermove=e=>{if(!drag)return;dialog.style.margin='0';dialog.style.left=Math.max(0,Math.min(innerWidth-100,drag.left+e.clientX-drag.x))+'px';dialog.style.top=Math.max(0,Math.min(innerHeight-50,drag.top+e.clientY-drag.y))+'px';};title.onpointerup=title.onpointercancel=()=>drag=null;
 dialog.addEventListener('pointerdown',()=>dialog.style.zIndex=String(z=Math.max(z,...[...document.querySelectorAll("dialog")].map(d=>Number(d.style.zIndex)||80))+1));dialog.addEventListener('keydown',e=>{if(e.key==='Escape'&&!(window.onboardingActive&&dialog.id==='settingsPageWindow')){dialog.close();e.stopPropagation();}});
 }
 document.querySelectorAll('dialog').forEach(floating);
 function open(id){const d=$(id);floating(d);if(!d.open)d.show();d.style.zIndex=String(z=Math.max(z,...[...document.querySelectorAll("dialog")].map(d=>Number(d.style.zIndex)||80))+1);}
 $('settingsGear').onclick=()=>{ui.openSettings('general');$('settingsPageWindow').style.zIndex=String(z=Math.max(z,...[...document.querySelectorAll("dialog")].map(d=>Number(d.style.zIndex)||80))+1);};
 const settings=category=>()=>{ui.openSettings(category);$('settingsPageWindow').style.zIndex=String(z=Math.max(z,...[...document.querySelectorAll("dialog")].map(d=>Number(d.style.zIndex)||80))+1);};
 const menus={
 File:[['Run initial setup again',()=>{$('runSetup').click();open('settingsPageWindow');}],['Backup / restore settings',settings('advanced')],['Exit',()=>window.close()]],
 Edit:[['Selected source properties',()=>open('sourceProperties')],['Move source forward',()=>$('canvasFront').click()],['Move source backward',()=>$('canvasBack').click()],['Lock / unlock source',()=>window.streamCanvas.toggleLock()]],
 View:[['Preview settings',settings('preview')],['Fullscreen',()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen()]],
 Panels:[],
 Tools:[['OBS Connection',settings('obs')],['Platform connections',settings('connections')],['Relay connection',settings('relay')],['Fallback & output',settings('output')],['Relay Admin',()=>{ui.setPage('admin');open('adminPageWindow');}]],
 Help:[['Quick guide',()=>open('quickHelp')],['About UniversalCollab',()=>open('aboutApp')]]
 };
 for(const[name,rows]of Object.entries(menus)){const d=make('details');d.className='app-menu';const summary=make('summary',name),list=make('div');list.className='menu-popup';list.setAttribute('role','menu');for(const[label,fn]of rows){const b=button(label,()=>{d.open=false;try{fn();}catch(e){note(e.message);}});b.setAttribute('role','menuitem');list.append(b);}d.append(summary,list);d.addEventListener('toggle',()=>{if(d.open)document.querySelectorAll('.app-menu').forEach(n=>{if(n!==d)n.open=false;});});$('appMenus').append(d);}
 document.addEventListener('pointerdown',e=>{if(!e.target.closest('.app-menu'))document.querySelectorAll('.app-menu').forEach(d=>d.open=false);});
 function info(id,title,text){const d=make('dialog');d.id=id;d.append(make('h2',title),make('p',text));document.body.append(d);floating(d);}
 info('quickHelp','Workspace guide','Drag a colored title bar into a highlighted left, center, right or bottom section. Panels controls visibility, adding panels and reset. Drag dividers between panels to resize. Sources are shown front to back; drag rows to reorder. Changes appear in the canvas immediately. Apply layout sends them to the relay. OBS scenes and sources control OBS separately.');
 info('aboutApp','UniversalCollab · rc.8','Self-hosted collaboration and streaming workspace. OBS preview is local, without audio, and does not show the final relay composite.');
 const prop=make('dialog');prop.id='sourceProperties';prop.append(make('h2','Relay source properties'),$('canvasInspector'));document.body.append(prop);floating(prop);
 // Resolution is server-side output configuration, not merely canvas zoom.
 function resolutionPaint(){const v=window.streamCanvas.snapshot().resolution;const select=$('layoutResolution');if(document.activeElement===select||['layoutResolutionWidth','layoutResolutionHeight'].includes(document.activeElement.id))return;const key=v?v.width+'x'+v.height:'auto';select.value=[...select.options].some(o=>o.value===key)?key:'custom';if(v){$('layoutResolutionWidth').value=v.width;$('layoutResolutionHeight').value=v.height;}customFields();$('resolutionStatus').textContent=v?'Output: '+v.width+' × '+v.height:'Output matches incoming feed';}
 function customFields(){for(const id of ['layoutResolutionWidth','layoutResolutionHeight'])$(id).parentElement.hidden=$('layoutResolution').value!=='custom';}
 $('layoutResolution').onchange=customFields;
 $('applyCanvas').onclick=()=>window.streamCanvas.save();
 $('applyResolution').onclick=async()=>{if(!connected){note('Connect to your relay first.');return;}if(view?.status?.broadcast){note('Stop OBS and end the relay broadcast before changing resolution.');return;}const choice=$('layoutResolution').value;const [w,h]=choice==='custom'?[Number($('layoutResolutionWidth').value),Number($('layoutResolutionHeight').value)]:choice.split('x').map(Number);if(choice!=='auto'&&(!Number.isInteger(w)||!Number.isInteger(h)||w<320||h<240||w>3840||h>3840||w%2||h%2||w*h>8294400)){note('Use even dimensions from 320 × 240, up to 3840 per side and 8.3 megapixels.');return;}const before=window.streamCanvas.snapshot().resolution;window.streamCanvas.resolution(choice==='auto'?null:{width:w,height:h});if(!await window.streamCanvas.save())window.streamCanvas.resolution(before);resolutionPaint();};
 window.addEventListener('relay-state',resolutionPaint);window.addEventListener('scene-change',resolutionPaint);resolutionPaint();
 // Drag dividers adjust section sizes, independently from panel movement.
 const docks=$('studioDocks');let sizes;try{sizes=JSON.parse(localStorage.getItem('uc-ui8-dock-sizes'));}catch{}sizes={left:sizes?.left||280,right:sizes?.right||200,bottom:sizes?.bottom||260};
 const applySizes=()=>{docks.style.setProperty('--left-width',Math.min(innerWidth*.28,sizes.left)+'px');docks.style.setProperty('--right-width',Math.min(innerWidth*.28,sizes.right)+'px');docks.style.setProperty('--bottom-height',Math.min(innerHeight*.42,sizes.bottom)+'px');};
 for(const side of ['left','right','bottom']){const handle=make('div');handle.className='dock-divider divider-'+side;handle.tabIndex=0;handle.setAttribute('role','separator');handle.setAttribute('aria-label','Resize '+side+' section');handle.setAttribute('aria-orientation',side==='bottom'?'horizontal':'vertical');docks.append(handle);let dragging=false;handle.onpointerdown=e=>{dragging=true;handle.setPointerCapture(e.pointerId);};handle.onpointermove=e=>{if(!dragging)return;const r=docks.getBoundingClientRect();sizes[side]=Math.max(side==='bottom'?100:150,side==='left'?e.clientX-r.left:side==='right'?r.right-e.clientX:r.bottom-e.clientY);applySizes();};handle.onpointerup=handle.onpointercancel=()=>{dragging=false;localStorage.setItem('uc-ui8-dock-sizes',JSON.stringify(sizes));};handle.onkeydown=e=>{const n=['ArrowRight','ArrowUp'].includes(e.key)?10:['ArrowLeft','ArrowDown'].includes(e.key)?-10:0;if(n){e.preventDefault();sizes[side]=Math.max(100,sizes[side]+n);applySizes();localStorage.setItem('uc-ui8-dock-sizes',JSON.stringify(sizes));}};}
 applySizes();window.addEventListener('resize',applySizes);
 const canvas=$('layoutPreview'),panel=$('canvasPanel');let fitting=false;
 function fitCanvas(){if(fitting)return;fitting=true;requestAnimationFrame(()=>{const ratio=canvas.style.aspectRatio.split('/').map(Number),aspect=ratio[0]/ratio[1]||16/9;const parent=canvas.parentElement;let extra=0;for(const n of parent.children)if(n!==canvas&&!n.hidden){const st=getComputedStyle(n);if(st.display!=='none')extra+=n.getBoundingClientRect().height+(parseFloat(st.marginTop)||0)+(parseFloat(st.marginBottom)||0);}const room=Math.max(70,parent.clientHeight-extra-20);const width=Math.max(80,Math.min(parent.clientWidth,room*aspect));canvas.style.width=width+'px';canvas.style.height=width/aspect+'px';fitting=false;});}
 new ResizeObserver(fitCanvas).observe(panel);new ResizeObserver(fitCanvas).observe($('resolutionBar'));window.addEventListener('scene-change',fitCanvas);window.addEventListener('relay-state',fitCanvas);fitCanvas();

 const btn=(text,label,fn)=>{const b=button(text,fn);b.title=label;b.setAttribute('aria-label',label);return b;};
 const fail=e=>note(e?.message||String(e));
 function dialog(id,title){const d=make('dialog');d.id=id;d.append(make('h2',title));document.body.append(d);floating(d);return d;}
 function setupLayout(){document.body.classList.toggle('onboarding',!!window.onboardingActive);$('studioPage').hidden=!!window.onboardingActive;$('settingsPageWindow').querySelector('.window-title strong').textContent=window.onboardingActive?'Welcome to UniversalCollab':'Settings';}
 window.addEventListener('setup-step',setupLayout);setupLayout();
 $('chooseAutoOBS').onclick=async()=>{const b=$('chooseAutoOBS');b.disabled=true;$('obsChoiceStatus').textContent='Looking for OBS…';$('obsMode').value='auto';$('obsMode').dispatchEvent(new Event('change'));try{if(!window.connectOBSAutomatically)throw Error('OBS control requires the desktop app.');await window.connectOBSAutomatically();$('obsChoiceStatus').textContent='OBS connected.';}catch(e){$('obsChoiceStatus').textContent='Pair OBS to finish automatic sync.';$('obsFeedback').textContent=e.message;$('automaticOBS').hidden=false;open('obsPairWindow');}finally{b.disabled=false;}};
 $('chooseManualOBS').onclick=()=>{$('obsMode').value='manual';$('obsMode').dispatchEvent(new Event('change'));$('obsChoiceStatus').textContent='Manual selected. Copy the relay URL and key in Settings → Relay.';if(window.obsConnected)$('obsDisconnect').click();};
 const pairButton=btn('OBS connection settings…','OBS connection settings',()=>{$('automaticOBS').hidden=false;open('obsPairWindow');});pairButton.id='manageOBS';$('obsSetupChoice').append(pairButton);
 window.addEventListener('obs-connection',()=>{if(window.obsConnected){$('obsChoiceStatus').textContent='OBS connected.';$('obsPairWindow').close();}});
 for(const id of ['newTab','existingTab'])$('joinAdvancedFields').prepend($(id));$('connect').textContent='Join relay';$('backLocal').addEventListener('click',()=>$('joinRelayWindow').close());
 window.addEventListener('relay-state',()=>{if(connected){$('joinRelayWindow').close();$('relayChoiceStatus').textContent='Connected to '+(selected()?.nickname||'relay');}});
 const developer=dialog('applicationConnections','Application connection setup');developer.append(make('p','For the app owner: configure registered OAuth clients here. Public releases should bundle the application IDs.'));
 for(const p of ['twitch','youtube']){const section=$('tab-'+p);section.hidden=true;developer.append($(p+'Setup').closest('details'));}
 $('advancedSettings').append(btn('Application connections…','Application connection setup',()=>open('applicationConnections')));
 window.addEventListener('platform-notice',e=>{$('linkFeedback').textContent=e.detail;if(!window.onboardingActive)note(e.detail);});
 const accountDialog=dialog('accountActions','Connected account');window.addEventListener('manage-platform',e=>{const p=e.detail;accountDialog.querySelectorAll('.account-action').forEach(n=>n.remove());const row=make('div');row.className='account-action';row.append(make('p',$(p+'Account').textContent),btn('Disconnect','Disconnect '+p,()=>{if(confirm('Disconnect this account?')){$(p+'Disconnect').click();accountDialog.close();}}));accountDialog.append(row);open('accountActions');});
 const authActions=make('div');$('connectionsPanel').append(authActions);window.addEventListener('platform-state',e=>{authActions.replaceChildren();for(const p of ['twitch','youtube']){const job=e.detail.auth?.[p];if(job?.status==='waiting')authActions.append(btn('Cancel '+p+' sign-in','Cancel '+p+' sign-in',()=>$(p+'Cancel').click()));if(job?.error)$('linkFeedback').textContent=job.error;}});
 for(const p of ['twitch','youtube']){const row=make('section');row.append(make('h3',p==='twitch'?'Twitch':'YouTube'));if(p==='youtube')row.append($('youtubeReload'),$('youtubeBroadcast').parentElement);row.append($(p+'ChatStart'),$(p+'ChatStop'),$(p+'ChatStatus'));$('chatConnections').append(row);}
 const custom=dialog('customPlatformWindow','Connect with a stream key');custom.append(make('p','Sign in to the platform in your browser, then copy its stream URL and key here.'),$('customConnectionForm'));
 const sites={Kick:'https://kick.com/',Restream:'https://app.restream.io/',Rumble:'https://rumble.com/'};for(const b of document.querySelectorAll('[data-custom-preset]'))b.addEventListener('click',async()=>{open('customPlatformWindow');const url=sites[b.dataset.customPreset];if(url)try{await window.relayDesktop?.studio('open-tool',{url});}catch(e){fail(e);}});$('customCancel').addEventListener('click',()=>custom.close());
 const compactContext=make('div');compactContext.id='compactContext';compactContext.hidden=true;compactContext.setAttribute('role','menu');document.body.append(compactContext);
 function contextMenu(event,actions){event?.preventDefault();compactContext.replaceChildren();for(const[label,fn,disabled]of actions){const b=btn(label,label,()=>{compactContext.hidden=true;Promise.resolve().then(fn).catch(fail);});b.disabled=!!disabled;b.setAttribute('role','menuitem');compactContext.append(b);}compactContext.hidden=false;const r=event?.currentTarget?.getBoundingClientRect();compactContext.style.left=Math.max(8,Math.min(innerWidth-compactContext.offsetWidth-8,event?.clientX||r?.left||20))+'px';compactContext.style.top=Math.max(8,Math.min(innerHeight-compactContext.offsetHeight-8,event?.clientY||r?.bottom||60))+'px';compactContext.querySelector('button:not(:disabled)')?.focus();}
 document.addEventListener('pointerdown',e=>{if(!compactContext.contains(e.target))compactContext.hidden=true;});document.addEventListener('keydown',e=>{if(e.key==='Escape')compactContext.hidden=true;});
 let namedAction=null;$('nameActionForm').onsubmit=e=>{e.preventDefault();const action=namedAction;namedAction=null;$('nameActionWindow').close();action?.($('nameActionValue').value.trim());};
 function askName(title,fn){$('nameActionTitle').textContent=title;$('nameActionValue').value='';namedAction=fn;open('nameActionWindow');$('nameActionValue').focus();}
 const sceneAction=(op,obs=false)=>{const prefix=obs?'obsScene':'scene',id=op==='New'?(obs?'obsSceneCreate':'sceneNew'):prefix+op;if(op==='Delete'){$(id).click();return;}askName(op+' '+(obs?'OBS':'relay')+' scene',name=>{$(obs?'obsSceneName':'sceneName').value=name;$(id).click();});};
 function bar(panel){const b=make('div');b.className='dock-actions';panel.append(b);return b;}
 const relayBar=bar($('scenePanel'));relayBar.append(btn('+','Add relay scene',()=>sceneAction('New')),btn('−','Delete relay scene',()=>sceneAction('Delete')),btn('⋯','More relay scene actions',e=>contextMenu(e,[['Rename',()=>sceneAction('Rename')],['Duplicate',()=>sceneAction('Duplicate')]])));
 $('sceneList').oncontextmenu=async e=>{e.preventDefault();await e.target.closest('button')?.onclick?.();contextMenu(e,[['Add scene',()=>sceneAction('New')],['Rename',()=>sceneAction('Rename')],['Duplicate',()=>sceneAction('Duplicate')],['Delete',()=>sceneAction('Delete')]]);};
 const obsBar=bar($('obsScenesPanel'));obsBar.append(btn('+','Add OBS scene',()=>sceneAction('New',true)),btn('−','Delete OBS scene',()=>sceneAction('Delete',true)),btn('⋯','More OBS scene actions',e=>contextMenu(e,[['Rename',()=>sceneAction('Rename',true)]])));
 $('obsScenes').oncontextmenu=e=>{const b=e.target.closest('button');if(b){$('obsEditScene').value=b.textContent;$('obsEditScene').dispatchEvent(new Event('change'));}contextMenu(e,[['Add scene',()=>sceneAction('New',true)],['Rename',()=>sceneAction('Rename',true)],['Delete',()=>sceneAction('Delete',true)]]);};
 const sourceActions=()=>[['Add source',()=>$('addItem').click()],['Properties',()=>open('sourceProperties')],['Lock / unlock',()=>window.streamCanvas.toggleLock()],['Move forward',()=>$('canvasFront').click()],['Move backward',()=>$('canvasBack').click()],['Remove',()=>$('canvasRemove').click()]];
 const sourceBar=bar($('sourcesPanel'));sourceBar.append(btn('+','Add relay source',()=>$('addItem').click()),btn('−','Remove selected source',()=>$('canvasRemove').click()),btn('⚙','Source properties',()=>open('sourceProperties')),btn('✓','Apply relay layout',()=>window.streamCanvas.save()));
 $('canvasLayers').oncontextmenu=e=>{e.target.closest('[data-layer]')?.querySelector('.source-name')?.click();contextMenu(e,sourceActions());};window.addEventListener('item-context',e=>{$('itemContext').hidden=true;contextMenu({preventDefault(){},clientX:e.detail.x,clientY:e.detail.y},sourceActions());});
 const obsProps=dialog('obsSourceProperties','OBS source properties');obsProps.append($('obsTransform'));const obsAdd=dialog('obsSourceAddWindow','Add OBS source');obsAdd.append($('obsExistingSource').parentElement,$('obsSourceAdd'));bar($('obsSourcesPanel')).append(btn('+','Add existing OBS source',()=>open('obsSourceAddWindow')),btn('⚙','OBS source properties',()=>open('obsSourceProperties')));
 $('obsSources').oncontextmenu=e=>{const row=e.target.closest('.obs-source-row');if(!row)return;row.querySelector('.source-name').click();const remove=[...row.querySelectorAll('button')].find(b=>b.textContent==='Remove');contextMenu(e,[['Properties',()=>open('obsSourceProperties')],['Move up',()=>row.querySelector('button[aria-label^="Raise "]')?.click()],['Move down',()=>row.querySelector('button[aria-label^="Lower "]')?.click()],['Remove',()=>remove?.click()]]);};
 const chatTools=make('span');chatTools.className='header-actions';const mod=btn('','Enable moderator controls',()=>{const active=$('chatSurface').classList.toggle('moderating');mod.setAttribute('aria-pressed',String(active));mod.title=active?'Disable moderator controls':'Enable moderator controls';});mod.innerHTML='<svg aria-hidden="true" viewBox="0 0 24 24"><path d="M12 2 4 5v6c0 5 8 11 8 11s8-6 8-11V5Z"/></svg>';mod.id='moderatorToggle';mod.setAttribute('aria-pressed','false');chatTools.append(mod,btn('⚙','Chat settings',()=>open('chatSettingsWindow')));$('chatSurface').querySelector('.dock-handle').append(chatTools);for(const b of chatTools.children)b.addEventListener('pointerdown',e=>e.stopPropagation());
 $('chatText').placeholder='Message';$('chatText').setAttribute('aria-label','Chat message');$('chatTarget').setAttribute('aria-label','Send message to platform');const send=$('chatSendForm').querySelector('button');send.textContent='➤';send.setAttribute('aria-label','Send chat message');send.title='Send chat message';document.body.append($('moderationConfirm'));
 $('newStream').addEventListener('click',()=>open('prepareStreamWindow'));window.addEventListener('stream-prepared',()=>$('prepareStreamWindow').close());
 const more=btn('⋯','More stream controls',e=>contextMenu(e,[['Past streams',()=>open('streamHistoryWindow')],['Check readiness',()=>$('readinessCheck').click()],['End relay broadcast',()=>$('end').click(),!connected],['Allow next broadcast',()=>$('allow').click(),!connected],['Refresh status',()=>$('refresh').click(),!connected]]));more.id='streamMore';$('streamsPanel').append(more);
 $('canvasHint').classList.add('visually-hidden');$('canvasHint').setAttribute('aria-live','polite');$('sourceProperties').append($('canvasHint'));$('obsPreviewStatus').classList.add('visually-hidden');$('applyCanvas').hidden=true;
 const addPanel=dialog('addPanelWindow','Add panel'),choices=make('div');addPanel.append(choices);const toolEditor=[...$('workspaceDialog').querySelectorAll(':scope>section')].find(n=>n.querySelector('input[placeholder="Tool name"]'));if(toolEditor)addPanel.append(toolEditor);
 function addChoices(){choices.replaceChildren();for(const[id]of ui.panels)if(ui.getWorkspace().hidden?.includes(id))choices.append(btn(ui.titles[id],'Show '+ui.titles[id],()=>{ui.setPanelVisible(id,true);addPanel.close();}));}
 const panelsMenu=[...document.querySelectorAll('.app-menu')].find(d=>d.querySelector('summary').textContent==='Panels');
 function panelMenu(){const list=panelsMenu.querySelector('.menu-popup');list.replaceChildren();for(const[id,p]of ui.panels){const label=make('label'),c=make('input');c.type='checkbox';c.checked=!ui.getWorkspace().hidden?.includes(id);c.setAttribute('aria-label','Show '+ui.titles[id]);c.onchange=()=>ui.setPanelVisible(id,c.checked);label.append(c,document.createTextNode(ui.titles[id]+(p.classList.contains('obs-panel')&&!window.obsConnected?' · OBS offline':'')));list.append(label);}list.append(btn('+ Add panel','Add panel',()=>{panelsMenu.open=false;addChoices();open('addPanelWindow');}),btn('Reset panels','Reset panels',()=>{panelsMenu.open=false;if(!confirm('Reset panel positions and sizes? Accounts and scenes are kept.'))return;weights={};sizes={left:280,right:200,bottom:260};localStorage.removeItem('uc-ui8-panel-weights');localStorage.removeItem('uc-ui8-dock-sizes');$('workspaceReset').click();applySizes();}));}
 panelsMenu.addEventListener('toggle',()=>{if(panelsMenu.open)panelMenu();});
 let weights={};try{weights=JSON.parse(localStorage.getItem('uc-ui8-panel-weights'))||{};}catch{}
 function separators(){for(const id of ['dockLeft','dockCenter','dockRight','dockBottom']){const column=$(id);column.querySelectorAll(':scope>.panel-separator').forEach(n=>n.remove());const visible=[...column.children].filter(n=>n.dataset.dock&&!n.hidden);visible.forEach(p=>{p.style.height='';p.style.flex=(weights[p.dataset.dock]||1)+' 1 0px';});for(let i=0;i<visible.length-1;i++){const a=visible[i],b=visible[i+1],horizontal=id==='dockBottom',sep=make('div');sep.className='panel-separator';sep.tabIndex=0;sep.setAttribute('role','separator');sep.setAttribute('aria-label','Resize '+ui.titles[a.dataset.dock]+' and '+ui.titles[b.dataset.dock]);sep.setAttribute('aria-orientation',horizontal?'vertical':'horizontal');a.after(sep);let drag=null;const measure=n=>horizontal?n.getBoundingClientRect().width:n.getBoundingClientRect().height;const start=pos=>{drag={pos,a:measure(a),total:measure(a)+measure(b),weights:(weights[a.dataset.dock]||1)+(weights[b.dataset.dock]||1)};};const resize=delta=>{if(!drag)return;const next=Math.max(65,Math.min(drag.total-65,drag.a+delta));weights[a.dataset.dock]=drag.weights*next/drag.total;weights[b.dataset.dock]=drag.weights*(drag.total-next)/drag.total;a.style.flex=weights[a.dataset.dock]+' 1 0px';b.style.flex=weights[b.dataset.dock]+' 1 0px';};const save=()=>{drag=null;localStorage.setItem('uc-ui8-panel-weights',JSON.stringify(weights));};sep.onpointerdown=e=>{if(e.button)return;start(horizontal?e.clientX:e.clientY);sep.setPointerCapture(e.pointerId);e.preventDefault();};sep.onpointermove=e=>{if(drag)resize((horizontal?e.clientX:e.clientY)-drag.pos);};sep.onpointerup=sep.onpointercancel=save;sep.onkeydown=e=>{const delta=(horizontal?{ArrowLeft:-15,ArrowRight:15}:{ArrowUp:-15,ArrowDown:15})[e.key];if(delta){e.preventDefault();start(0);resize(delta);save();}};}}fitCanvas();}
 window.addEventListener('panels-changed',()=>{separators();if(panelsMenu.open)panelMenu();});separators();document.body.dataset.compactReady='true';

})().catch(e=>{document.getElementById('bootMessage').textContent='Workspace could not start: '+e.message;document.getElementById('bootStatus').hidden=false;});
